###GET
Post http://localhost:4040
Content-Type: application/json

{
"user":"cyn",
"password":"Matthias"
}

###
POST http://localhost:4040/users
Content-Type: application/json

{
"gender":"male",
"firstname":"Torge",
"lastname":"Baumann",
"email":"torge@online.de",
"user":"tajb",
"password":"Elodie",
"dateOfBirth":"2012-01-23"
}