###GET
GET http://localhost:4040
###
POST http://localhost:4040
Content-Type: application/json

{
"gender":"male",
"firstname":"Matthias",
"lastname":"Baumann",
"email":"mcbaumann@online.de",
"username":"mcb",
"password":"Cynthia",
"dateOfBirth":"1984-04-18"
}